export const AdvocaciaProducts = [
  {
    name: 'Cafeteira',
    preco: 300,
    imagem: 'x',
    id: 1,
    tipo: 'objeto',
    mX: 0.2,
    dX: 0,
    level: 1,
    desc: 'Aumenta o multiplicador dos ganhos em 1',
    energia: 15,
    consumo: 0,
    produz: 25,
  },
  {
    name: 'Raul',
    preco: 3500,
    imagem: 'x',
    id: 2,
    tipo: 'pessoa',
    mX: 0,
    dX: 1.5,
    level: 1,
    desc: 'Aumenta o multiplicador de dinheiro em 2',
    energia: 50,
    consumo: 5,
    produz: 0,
  },
  {
    name: 'Jefinho',
    preco: 5000,
    imagem: 'x',
    id: 3,
    tipo: 'pessoa',
    mX: 0,
    dX: 2,
    level: 1,
    desc: 'Aumenta o multiplicador de dinheiro e os ganhos em 1',
    energia: 60,
    consumo: 4,
    produz: 0,
  },
  {
    name: 'StarLink Wifi',
    preco: 2000,
    imagem: 'x',
    id: 4,
    tipo: 'objeto',
    mX: 2,
    dX: 0,
    level: 1,
    desc: 'Aumenta o multiplicador de ganhos em 2',
    energia: 50,
    consumo: 0,
    produz: 0,
  },
  {
    name: 'Claro Wifi',
    preco: 200,
    imagem: 'x',
    id: 5,
    tipo: 'objeto',
    mX: 0.1,
    dX: 0,
    level: 1,
    desc: 'Aumenta o multiplicador de ganhos em 1',
    energia: 10,
    consumo: 0,
    produz: 0,
  },
  {
    name: 'Melhoria no computador',
    preco: 600,
    imagem: 'x',
    id: 7,
    tipo: 'melhoria',
    mX: 0.5,
    dX: 0,
    level: 1,
    desc: 'Aumenta o multiplicador dos ganhos em 1',
    energia: 20,
    consumo: 0,
    produz: 0,
  },
];
