export const AdvocaciaProducts = [
  {
    name: 'Cafeteira',
    preco: 250,
    imagem: 'x',
    id: 1,
    tipo: 'objeto',
    mX: 1,
    dX: 0,
    level: 1,
    desc: 'Aumenta o múltiplicador dos ganhos em 1',
  },
  {
    name: 'Raul',
    preco: 2500,
    imagem: 'x',
    id: 2,
    tipo: 'pessoa',
    mX: 0,
    dX: 2,
    level: 1,
    desc: 'Aumenta o múltiplicador de dinheiro em 2',
  },
  {
    name: 'Jefinho',
    preco: 5000,
    imagem: 'x',
    id: 3,
    tipo: 'pessoa',
    mX: 1,
    dX: 1,
    level: 1,
    desc: 'Aumenta o múltiplicador de dinheiro e os ganhos em 1',
  },
  {
    name: 'StarLink Wifi',
    preco: 2000,
    imagem: 'x',
    id: 4,
    tipo: 'objeto',
    mX: 2,
    dX: 0,
    level: 1,
    desc: 'Aumenta o múltiplicador de ganhos em 2',
  },
  {
    name: 'Claro Wifi',
    preco: 200,
    imagem: 'x',
    id: 5,
    tipo: 'objeto',
    mX: 1,
    dX: 0,
    level: 1,
    desc: 'Aumenta o múltiplicador de ganhos em 1',
  },
  {
    name: 'Capsula de Café 10u',
    preco: 200,
    imagem: 'x',
    id: 6,
    tipo: 'objeto temporario',
    mX: 0,
    dX: 0,
    level: 1,
    desc: '10 unidades de capsulas de café',
  },
  {
    name: 'Melhoria no computador',
    preco: 370,
    imagem: 'x',
    id: 7,
    tipo: 'melhoria',
    mX: 1,
    dX: 0,
    level: 1,
    desc: 'Aumenta o múltiplicador dos ganhos em 1',
  },
];
